# Introduction to Data Science L3
## Quick Introduction to Pandas
__Budapest 2021.09.23__ (*Fall Semester*).

**Notes:**
Dear (quick) learner, feel free to go over this notebook and run the cells on your own. There are some cells containing several statements without using the print function, thus, I encourage you to comment and uncomment some of them to check the outputs of each statement within the same code-block. Also note that some blocks are going to throw some Errors/Exceptions, this, on most of the cases should be on purpose, read the error and try to understand what happened. ;)

Main Source: [Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/)

Additional Sources:
- [Doc from pandas.pydata.org](https://pandas.pydata.org/docs/)
- [Quick Start from pandas.pydata.org]

Regards,<br/>Andrea Galloni<br/>andrea.galloni@inf.elte.hu


----

## Pandas
**Pandas** is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool, built on top of the Python programming language... *Pandas is biuld on top of NumPy!*

### Pandas vs NumPy
*As we saw, NumPy's ndarray data structure provides essential features for the type of clean, well-organized data typically seen in numerical computing tasks.* While it serves this purpose very well, its limitations become clear when we need more flexibility (e.g., attaching labels to data, working with missing data, etc.) and when attempting operations that do not map well to element-wise broadcasting (e.g., groupings, pivots, etc.), each of which is an important piece of analyzing the less structured data available in many forms in the world around us.


### Main Features
Here are just a few of the things that pandas does well:

  - Easy *handling of missing data* in floating point as well as non-floating
    point data.
  - *Size mutability:* columns can be inserted and deleted from DataFrame and
    higher dimensional objects
  - Automatic and explicit data alignment: objects can be explicitly aligned
    to a *set of labels*, or the user can simply ignore the labels and let
    `Series`, `DataFrame`, etc. automatically align the data for you in
    computations.
  - Powerful, *flexible group by functionality to perform split-apply-combine
    operations on data sets*, for both aggregating and transforming data.
  - Make it easy to convert ragged, differently-indexed data in other Python
    and NumPy data structures into DataFrame objects.
  - Intelligent *label-based slicing, fancy indexing, and subsetting of large
    data sets*.
  - Intuitive *merging and joining data sets*.
  - Flexible reshaping and pivoting of data sets.
  - Hierarchical labeling of axes (possible to have multiple labels per tick).
  - Robust IO tools for loading data from flat files (CSV and delimited),
    Excel files, databases, and saving/loading data from the ultrafast HDF5
    format.
  - *Time series-specific functionality:* date range generation and frequency
    conversion, moving window statistics, moving window linear regressions,
    date shifting and lagging, etc.


### Pandas DataFrame
The main data object used within pandas is the `DataFrame`. A `DataFrame`s are essentially **multidimensional arrays with attached row and column labels**, and often with *heterogeneous types and/or missing data*. As well as offering a convenient storage interface for labeled data, Pandas implements a number of powerful data operations familiar to users of both database frameworks and spreadsheet programs. Beside `DataFrames` pandas implement a more basic data object called `Series`.


In [27]:
import pandas as pd
pd.__version__

'0.24.2'

### Pandas Objects
At the very basic level, Pandas objects can be thought of as enhanced versions of NumPy structured arrays in which the rows and columns are identified with labels rather than simple integer indices.

### The Pandas `Series` Object
*A Pandas Series is a one-dimensional array of indexed data.*

In [28]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

As we see in the output, the Series wraps both a sequence of values and a sequence of indices, which we can access with the values and index attributes. The values are simply a familiar NumPy array:

In [29]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

The `index` object is an array-like object of type `pd.Index`.

In [30]:
index=data.index
index

RangeIndex(start=0, stop=4, step=1)

In [31]:
# Like with a NumPy array, data can be accessed by the associated index via the familiar Python square-bracket notation:

print(data[1],'\n')
print(data[1:3])

0.5 

1    0.50
2    0.75
dtype: float64


### Pandas Series as generalized NumPy array!

From what we've seen so far, it may look like the Series object is basically interchangeable with a one-dimensional NumPy array. The essential difference is the presence of the index: while the Numpy Array has an **implicitly defined integer index** used to access the values, the Pandas `Series` has an **explicitly defined index associated with the values**.


This explicit index definition gives the Series object additional capabilities. For example, the index need not be an integer, but can consist of values of any desired type. 

In [32]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [33]:
data['a']

0.25

In [34]:
data.b

0.5

In [35]:
# We can even use non-contiguous or non-sequential indices:

data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=[2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [36]:
# what if the index key does not exist?
data[4]

KeyError: 4

### Pandas Series as a specialized Python Dict

In [38]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [39]:
population.California

38332521

In [40]:
# slicing works on the index!
population['California':'Illinois']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [43]:
# contructing a Series Object
pd.Series(data.values, index=[1,2,3,4])

1    0.25
2    0.50
3    0.75
4    1.00
dtype: float64

In [44]:
pd.Series([2, 4, 6])


0    2
1    4
2    6
dtype: int64

In [45]:
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [46]:
# data can be a dictionary as well!
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

In [47]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])

3    c
2    a
dtype: object

### The `DataFrame` Object

The next fundamental structure in Pandas is the `DataFrame`. Like the `Series` object, the `DataFrame` can be thought of either as a generalization of a NumPy array, or as a specialization of a Python dictionary.


If a `Series` is an analog of a one-dimensional array with flexible indices, a `DataFrame` **is an analog of a two-dimensional array with both flexible row indices and flexible column names.** Just as you might think of a two-dimensional array as an ordered sequence of aligned one-dimensional columns, you can think of a DataFrame as a sequence of aligned Series objects. Here, by "aligned" we mean that they share the same index.

In [48]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

Now that we have this along with the population Series from before, we can use a dictionary to construct a single two-dimensional object (`DataFrame`) containing this information:

In [49]:
states = pd.DataFrame({'population': population,
                       'area': area})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [50]:
# Like the Series object, the DataFrame has an index attribute that gives access to the index labels:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [51]:
# Additionally, the DataFrame has a columns attribute, which is an Index object holding the column labels:
states.columns

Index(['population', 'area'], dtype='object')

### DataFrame as specialized dictionary
Similarly, we can also think of a `DataFrame` as a specialization of a dictionary. Where a dictionary maps a key to a value, a `DataFrame` maps a column name to a `Series` of column data. For example, asking for the 'area' attribute returns the Series object containing the areas we saw earlier:

In [52]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [57]:
# DataFrame Construction from Series
pd.DataFrame(population, columns=['population'])

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [63]:
# DataFrame Construction from Dict
data = [{'a': i, 'b': 2 * i}
        for i in range(5)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4
3  3  6
4  4  8

In [64]:
# in case of missing values Pandas will try to fill with NaN
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])


a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [65]:
# from a dictionary of series
pd.DataFrame({'population': population,
              'area': area})

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [67]:
# from two dimensional numpy array
import numpy as np
pd.DataFrame(np.random.rand(3, 2),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c'])

foo       bar
a  0.935028  0.775754
b  0.432726  0.919564
c  0.405933  0.415412

### Pandas Index Object!

We have seen here that both the `Series` and `DataFrame` objects contain an explicit index that lets you reference and modify data. This `Index` object is an interesting structure in itself, and it can be thought of either as an **immutable array** or as an ordered set (technically a multi-set, as Index objects may contain repeated values). Those views have some interesting consequences in the operations available on Index objects. As a simple example, let's construct an Index from a list of integers:

In [68]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [69]:
ind[1]


3

In [70]:
ind[::2]


Int64Index([2, 5, 11], dtype='int64')

In [71]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)


5 (5,) 1 int64


In [73]:
# indices are immutable!!!
ind[1] = 0
# This immutability makes it safer to share indices between multiple DataFrames and arrays, without the potential for side effects from inadvertent index modification.

TypeError: Index does not support mutable operations

### Index as an ordered (multi-)set 
Numpy arrays contain some self attributes useful while coding. 

In [78]:
indA = pd.Index([1, 3, 5, 7, 7])
indB = pd.Index([2, 3, 5, 7, 11])
indA & indB  # intersection

Int64Index([3, 5, 7, 7], dtype='int64')

In [79]:
indA | indB  # union

Int64Index([1, 2, 3, 5, 7, 7, 11], dtype='int64')

In [80]:
indA ^ indB  # symmetric difference

Int64Index([1, 2, 11], dtype='int64')

In [81]:
# These operations may also be accessed via object methods, for example:
indA.intersection(indB)

Int64Index([3, 5, 7, 7], dtype='int64')

## Data Indexing and Selection

In [82]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [84]:
data['b']

0.5

In [86]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [87]:
data.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [89]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [90]:
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [91]:
# slicing by explicit index
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [92]:
# slicing by implicit integer index
data[0:2]

a    0.25
b    0.50
dtype: float64

In [93]:
# fancy indexing
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

**NOTE: Among these, slicing may be the source of the most confusion. Notice that when slicing with an explicit index (i.e., `data['a':'c']`), the final index is included in the slice, while when slicing with an implicit index (i.e., `data[0:2]`), the final index is excluded from the slice.**

### Indexers: loc, iloc, and ix

These slicing and indexing conventions can be a source of confusion. For example, if your Series has an explicit integer index, an indexing operation such as `data[1]` will use the explicit indices, while a slicing operation like `data[1:3]` will use the implicit Python-style index.

In [96]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [95]:
# explicit index when indexing
data[1]

'a'

In [97]:
# implicit index when slicing
data[1:3]

3    b
5    c
dtype: object

Because of this potential confusion in the case of integer indexes, Pandas provides some special indexer attributes that explicitly expose certain indexing schemes. These are not functional methods, but attributes that expose a particular slicing interface to the data in the Series.

First, the `loc` attribute allows indexing and slicing that always references the explicit index:


In [98]:
data.loc[1]

'a'

In [99]:
data.loc[1:3]

1    a
3    b
dtype: object

The `iloc` attribute allows indexing and slicing that always references the implicit Python-style index:

In [100]:
data.iloc[1]

'b'

In [101]:
data.iloc[1:3]

3    b
5    c
dtype: object

One guiding principle of Python code is that **"explicit is better than implicit.**" The explicit nature of `loc` and `iloc` make them very useful in **maintaining clean and readable code**; especially in the case of integer indexes, I recommend using these both to make code easier to read and understand, and to prevent subtle bugs due to the mixed indexing/slicing convention.

In [ ]:
### Data Selection in DataFrame

In [102]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

The individual `Series` that make up the *columns of the `DataFrame`* can be accessed via dictionary-style indexing of the column name:

In [103]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [104]:
# also attribute-style works:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [105]:
data.area is data['area']

True

Though this is a useful shorthand, **keep in mind that it does not work for all cases!** For example, if the column names are not strings, or if the column names **conflict with methods** of the `DataFrame`, this *attribute-style access is not possible*. For example, the `DataFrame` has a `pop()` method, so data.pop will point to this rather than the "pop" column:

In [107]:
data.pop is data['pop']

False

In particular, you should avoid the temptation to try column assignment via attribute (i.e., use `data['pop'] = z` rather than `data.pop = z`).

In [108]:
data['density'] = data['pop'] / data['area']
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [109]:
# DataFrame as two-dimensional array
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [110]:
# Transpose the DataFrame
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [111]:
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [113]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [112]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

### Concatenation of arrays

Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routines ``np.concatenate``, ``np.vstack``, and ``np.hstack``.
``np.concatenate`` takes a tuple or list of arrays as its first argument, as we can see here:

In [ ]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y]) # works also for several arrays to concatenate! 

For `array-style` indexing, we need another convention. Here Pandas again uses the `loc`, `iloc`, and `ix` indexers. Using the `iloc` indexer, we can index the underlying array as if it is a simple NumPy array, but the `DataFrame` index and column labels are maintained in the result!

In [114]:
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [115]:
data.iloc[:3, :2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [117]:
data.loc[:'New York', :'pop']

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [118]:
data.ix[:3, :'pop']

/home/andrea/MyBins/Anaconda3/envs/SynthGen/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

Any of the familiar NumPy-style data access patterns can be used within these indexers. For example, in the `loc` indexer we can combine masking and fancy indexing:

In [119]:
data.loc[data.density > 100, ['pop', 'density']]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

Any of these indexing conventions may also be used to set or modify values; this is done in the standard way that you might be accustomed to from working with NumPy:

In [120]:
data.iloc[0, 2] = 90
data

area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

There are a couple extra indexing conventions that might seem at odds with the preceding discussion, but nevertheless can be very useful in practice. First, while indexing refers to columns, slicing refers to rows:

In [121]:
data['Florida':'Illinois']

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [122]:
# Such slices can also refer to rows by number rather than by index:
data[1:3]

area       pop     density
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746

Similarly, direct masking operations are also interpreted row-wise rather than column-wise:

In [123]:
data[data.density > 100]

area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121

### Ufuncs Index Preservation

Because Pandas is designed to work with NumPy, any NumPy `ufunc` will work on Pandas `Series` and `DataFrame` objects. Let's start by defining a simple Series and `DataFrame` on which to demonstrate this:

In [125]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int64

In [126]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
                  columns=['A', 'B', 'C', 'D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [127]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [128]:
np.sin(df * np.pi / 4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

For binary operations on two `Series` or `DataFrame` objects, Pandas will align `indices` in the process of performing the operation. This is very convenient when working with incomplete data, as we'll see in some of the examples that follow.

In [129]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name='population')

In [130]:
area

Alaska        1723337
Texas          695662
California     423967
Name: area, dtype: int64

In [131]:
population

California    38332521
Texas         26448193
New York      19651127
Name: population, dtype: int64

In [132]:
population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

it contains the union of the indices if an entry is missing then it will be replaced with `NaN`

In [133]:
area.index | population.index

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [134]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [136]:
# just in case we don't like the standard behavior
A.add(B, fill_value=0)


0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

The following table lists the arithmetic operators implemented in NumPy:

| Operator	    | Equivalent ufunc    | Description                           |
|---------------|---------------------|---------------------------------------|
|``+``          |``np.add``           |Addition (e.g., ``1 + 1 = 2``)         |
|``-``          |``np.subtract``      |Subtraction (e.g., ``3 - 2 = 1``)      |
|``-``          |``np.negative``      |Unary negation (e.g., ``-2``)          |
|``*``          |``np.multiply``      |Multiplication (e.g., ``2 * 3 = 6``)   |
|``/``          |``np.divide``        |Division (e.g., ``3 / 2 = 1.5``)       |
|``//``         |``np.floor_divide``  |Floor division (e.g., ``3 // 2 = 1``)  |
|``**``         |``np.power``         |Exponentiation (e.g., ``2 ** 3 = 8``)  |
|``%``          |``np.mod``           |Modulus/remainder (e.g., ``9 % 4 = 1``)|

Additionally there are Boolean/bitwise operators; we will explore these in [Comparisons, Masks, and Boolean Logic](02.06-Boolean-Arrays-and-Masks.ipynb).

In [ ]:
x = np.array([-2, -1, 0, 1, 2]) # absolute value
abs(x) # pure python
np.absolute(x) # numpy (the actual implementation may be different!!!)
np.abs(x) # but also this method, same!

In [137]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)),
                 columns=list('AB'))
A

A   B
0  1  11
1  5   1

In [138]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)),
                 columns=list('BAC'))
B

B  A  C
0  4  0  9
1  5  8  0
2  9  2  6

In [139]:
A + B

A     B   C
0   1.0  15.0 NaN
1  13.0   6.0 NaN
2   NaN   NaN NaN

In [140]:
fill = A.stack().mean()
A.add(B, fill_value=fill)

A     B     C
0   1.0  15.0  13.5
1  13.0   6.0   4.5
2   6.5  13.5  10.5

In [143]:
print(A)
A.stack()

   A   B
0  1  11
1  5   1


0  A     1
   B    11
1  A     5
   B     1
dtype: int64

### Ufuncs: Operations Between DataFrame and Series

When performing operations between a `DataFrame` and a `Series`, the index and column alignment is similarly maintained. Operations between a `DataFrame` and a `Series` are similar to operations between a two-dimensional and one-dimensional NumPy array. Consider one common operation, where we find the difference of a two-dimensional array and one of its rows:

In [144]:
A = rng.randint(10, size=(3, 4))
A

array([[3, 8, 2, 4],
       [2, 6, 4, 8],
       [6, 1, 3, 8]])

In [145]:
A - A[0]

array([[ 0,  0,  0,  0],
       [-1, -2,  2,  4],
       [ 3, -7,  1,  4]])

In [146]:
df = pd.DataFrame(A, columns=list('QRST'))
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -1 -2  2  4
2  3 -7  1  4

In [147]:
df.subtract(df['R'], axis=0)

Q  R  S  T
0 -5  0 -6 -4
1 -4  0 -2  2
2  5  0  2  7

In [148]:
halfrow = df.iloc[0, ::2]
halfrow

Q    3
S    2
Name: 0, dtype: int64

In [149]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -1.0 NaN  2.0 NaN
2  3.0 NaN  1.0 NaN

### Missing Data!?!?!

In [150]:
vals1 = np.array([1, None, 3, 4])
vals1

array([1, None, 3, 4], dtype=object)

In [153]:
vals1.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [154]:
vals2 = np.array([1, np.nan, 3, 4]) 
vals2.dtype

dtype('float64')

In [155]:
1 + np.nan

nan

In [156]:
0 *  np.nan

nan

In [157]:
vals2.sum(), vals2.min(), vals2.max()


(nan, nan, nan)

In [158]:
np.nansum(vals2), np.nanmin(vals2), np.nanmax(vals2)

(8.0, 1.0, 4.0)

In [159]:
pd.Series([1, np.nan, 2, None])


0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

`NaN` and `None` both have their place, and Pandas is built to handle the two of them nearly interchangeably, converting between them where appropriate:

In [160]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [162]:
x = pd.Series(range(2), dtype=int)
x

0    0
1    1
dtype: int64

In [163]:
x[0] = None
x

0    NaN
1    1.0
dtype: float64

### Detecting nulls!
Pandas data structures have two useful methods for detecting null data: `isnull()` and `notnull()`. Either one will return a Boolean mask over the data. For example:

In [166]:
data = pd.Series([1, np.nan, 'hello', None])
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [167]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [168]:
# filter not NaN(s)
data[data.notnull()]

0        1
2    hello
dtype: object

In [169]:
# drop rows containing NaN(s) 
data.dropna()

0        1
2    hello
dtype: object

We cannot drop single values from a DataFrame; we can only drop full rows or full columns. Depending on the application, you might want one or the other, so `dropna()` gives a number of options for a DataFrame:

In [170]:
df = pd.DataFrame([[1,      np.nan, 2],
                   [2,      3,      5],
                   [np.nan, 4,      6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [172]:
df.dropna()

0    1  2
1  2.0  3.0  5

In [171]:
df.dropna(axis='columns')

2
0  2
1  5
2  6

In [173]:
df[3] = np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [174]:
df.dropna(axis='columns', how='all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [175]:
df.dropna(axis='rows', thresh=3)

0    1  2   3
1  2.0  3.0  5 NaN

### Filling Null Values

In [176]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [177]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [178]:
# forward-fill
data.fillna(method='ffill')

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [179]:
# back-fill
data.fillna(method='bfill')

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [180]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [181]:
df.fillna(method='ffill', axis=1)

0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

In [ ]:
# Multi Indexing! 